version: 1.1
kind: operation
name: build-plx-streamlit-huggingface-app
params:
  destination:
    connection: "docker-connection"
    value: polyaxon-examples:plx-streamlit-huggingface-app
  context:
    value: "{{ globals.artifacts_path }}/plx-streamlit-huggingface-app"
runPatch:
  init:
    - git:
        url: "https://github.com/avivkri/plx-streamlit-huggingface-app"
hubRef: kaniko

